// <auto-generated />
namespace eCommerce.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class some_changes_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(some_changes_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202010091806082_some_changes_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
